### ISSUE TITLE
Additional Feature: Supporting the -c and --config  arguments for config files

### ISSUE THREAD

**Issue by Namatuzio** [Pasqua101/txt-to-HTML-converter#18]
Hey, @Pasqua101 I'd like to work on a new feature that will allow TOML configuration files to be passed as arguments, allowing for multiple arguments to be parsed easily. 
The argument will be accessible using either -c or --config and I'll be using the tomllib library to parse the config files.

Let me know what you think!

**Comment by Pasqua101** [comment]
Hey @Namatuzio, sounds good. I have no objections with your idea. Please go ahead.

**Comment by Pasqua101** [comment]
Thanks. Tested it out and merged it into the repo.
