### ISSUE TITLE
Processing a directory outputs a message for every file in the directory

### ISSUE THREAD

**Issue by rook4715** [Pasqua101/txt-to-HTML-converter#2]
Input:
![image](https://github.com/Pasqua101/txt-to-HTML-converter/assets/100863301/25988c4a-3c76-4c1d-9776-26c3ef15769e)

Message from running the tool:
![image](https://github.com/Pasqua101/txt-to-HTML-converter/assets/100863301/1f2984a0-8f20-4403-a8df-8d131cc1ae22)

Output:
![image](https://github.com/Pasqua101/txt-to-HTML-converter/assets/100863301/66823457-61f8-4a8f-8c43-b45f3e5fdf5d)

The tool processes a directory correctly, but it should only output conversion messages when processing .txt files.

**Comment by Pasqua101** [comment]
Fixed it. I was trying to have it where it would let the user know that it converted x number of files. But I changed my mind about it later and forgot to change it.
