### ISSUE TITLE
Tool errors when processing a file in a directory

### ISSUE THREAD

**Issue by rook4715** [Pasqua101/txt-to-HTML-converter#3]
Try to convert a .txt file nested in a directory.
It will result in an error:
![image](https://github.com/Pasqua101/txt-to-HTML-converter/assets/100863301/6a75e388-58d8-4510-ad23-6a732a0cbb01)

**Comment by Pasqua101** [comment]
Thanks for pointing out the bug. I fixed the way it handles the creation of the path for the output file.  I've tested it out the same command and it worked for me. So this issue should be solved.
