### ISSUE TITLE
Clarity on running program in README

### ISSUE THREAD

**Issue by rook4715** [Pasqua101/txt-to-HTML-converter#4]
The README doesn't explain how to install/build the `txt_to_html` program locally.

How I understood the README:
Step 1: Install Python locally
Step 2: Add Python to environment variables
Step 3: Run the program using `txt_to_html filename.txt` or `txt_to_html foldername`

(When and how was the program built?)

(For what it's worth, I ran the program by downloading the .py file and running it with `python txt_to_html.py filename.txt`)

**Comment by Pasqua101** [comment]
Yeah, turns out my method was wrong. I tired searching for a way to run the program like in your example, but all my methods didn't work. So for now, it has to be ran like so `python txt_to_html.py filename.txt`. I have updated the README to reflect this.
