### ISSUE TITLE
Commenting

### ISSUE THREAD

**Issue by rook4715** [Pasqua101/txt-to-HTML-converter#5]
When looking at the source code, I felt that the comments made it a little cluttered.
Commenting is good for explaining why a program does something a certain way and documenting what a function does, but there's no need to explain what every single line of code is doing.

**Comment by Pasqua101** [comment]
Fair enough. When I write my code, I leave a lot of comments for myself so I can understand what was being done. I also like leaving it there to explain to others looking at my code what was done. However, it can get messy. So, a lot of the unnecessary comments or ones that we're left as notes to self have been removed.
